import os
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig, GenerationConfig, BitsAndBytesConfig, AutoProcessor
import docx
import re
from tqdm import tqdm
import time
import argparse
import numpy as np


"""
===== USAGE EXAMPLES =====

This script calculates token probabilities using existing reasoning from a CSV file.

python llm_logit.py --input_csv "[LLM classification output(csv)]" --model_id "[model name]" --output_csv "[output file name]"

Required CSV columns:
- utterance_id: Unique identifier for each utterance
- timestamp: Time when utterance was made 
- name: Speaker name
- utterance: The actual utterance text
- group: Group identifier
- date: Date of the conversation
- llm_reasoning: Existing reasoning text generated by LLM

Output includes all original columns plus:

Sequence-based Logits (from DEBUG normalized logits):
- logit_explain_own_idea: Log probability for 'Explain Own Idea'
- logit_engage_others_low: Log probability for 'Engage Others Idea (LOW)'
- logit_engage_others_medium: Log probability for 'Engage Others Idea (MEDIUM)'
- logit_engage_others_high: Log probability for 'Engage Others Idea (HIGH)'
- logit_uncorrelated: Log probability for 'Uncorrelated'

Next-token Probabilities (from DEBUG next-token probs):
- tokprob_explain_own_idea: EXP probability (first token " Explain")
- tokprob_engage_others: EOI probability (first token " Engage")
- tokprob_uncorrelated: UC probability (first token " Uncorrelated")
- tokprob_engage_low: EOI-L probability (token "LOW" after "Engage Others Idea (")
- tokprob_engage_medium: EOI-M probability (token "MEDIUM")
- tokprob_engage_high: EOI-H probability (token "HIGH")

Normalized Probabilities (softmax of sequence logits):
- prob_explain_own_idea/prob_engage_others_low/prob_engage_others_medium/prob_engage_others_high/prob_uncorrelated

Other:
- llm_classification_output_line_new: New classification line generated during processing
- parsed_* columns are automatically removed from output
"""

def clean_reasoning_text(reasoning):
    return re.sub(r'^\s*Reasoning\s*[:\.]?\s*', '', reasoning, flags=re.IGNORECASE)

# --- 1. Docx parser ---
def extract_dialogue_from_docx(docx_path):
    doc = docx.Document(docx_path)
    full_text = [paragraph.text for paragraph in doc.paragraphs]
    text = '\n'.join(full_text)

    chunks = re.split(
        r'(\n+\d{1,2}:\d{2}(?::\d{2})?\s*\n|\n+\d{1,2}:\d{2}(?::\d{2})?\s*$|^\d{1,2}:\d{2}(?::\d{2})?\s*\n)',
        text, flags=re.MULTILINE
    )

    timestamps, speakers, utterances = [], [], []
    current_timestamp = None

    for chunk in chunks:
        clean_chunk = chunk.strip('\n').strip()
        
        if re.fullmatch(r"\d{1,2}:\d{2}(?::\d{2})?", clean_chunk):
            current_timestamp = clean_chunk
        else:
            lines = [l.strip() for l in chunk.split('\n') if l.strip()]
            i = 0
            while i < len(lines):
                line = lines[i]
                
                match = re.match(r'^([A-Za-z가-힣]+):\s*(.+)', line)
                if match:
                    speaker, utterance = match.group(1), match.group(2)
                    utterance = re.sub(r'\s+', ' ', utterance)
                    timestamps.append(current_timestamp)
                    speakers.append(speaker)
                    utterances.append(utterance)
                
                elif re.match(r'^\d{1,2}:\d{2}(?::\d{2})?\s+\[.+\]$', line):
                    ts, desc = re.match(r'^(\d{1,2}:\d{2}(?::\d{2})?)\s+(\[.+\])$', line).groups()
                    current_timestamp = ts
                    timestamps.append(current_timestamp)
                    speakers.append("NARRATION")
                    utterances.append(desc)
                
                elif re.match(r'^\[.+\]$', line):
                    timestamps.append(current_timestamp)
                    speakers.append("NARRATION")
                    utterances.append(line)
                i += 1
    df = pd.DataFrame({'timestamp': timestamps, 'name': speakers, 'utterance': utterances})
    df = df[df.name != "NARRATION"].reset_index(drop=True)
    return df


# --- 2. Model load ---
def load_model_and_tokenizer(model_id):
    model_id_lower = model_id.lower()    
    print(f"Loading tokenizer for {model_id}...")
    tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)        
    if tokenizer.model_max_length is None or tokenizer.model_max_length > 4096 * 128:
        tokenizer.model_max_length = 4096 * 128
        print(f"Adjusted other model_max_length to {tokenizer.model_max_length}")

    if tokenizer.pad_token is None:
        if tokenizer.eos_token is not None:
            tokenizer.pad_token = tokenizer.eos_token
            print(f"Tokenizer pad_token was None, set to eos_token: '{tokenizer.pad_token}' (ID: {tokenizer.eos_token_id})")
        else:
            tokenizer.add_special_tokens({'pad_token': '[PAD]'})
            print(f"Tokenizer pad_token and eos_token were None. Added pad_token: {tokenizer.pad_token} (ID: {tokenizer.pad_token_id})")

    print(f"Loading model {model_id}...")
    model_kwargs = {
        "device_map": "auto",
        "trust_remote_code": True
    }

    if "llama-3" in model_id_lower:
        model_kwargs["torch_dtype"] = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    elif "phi" in model_id_lower: 
        model_kwargs["torch_dtype"] = "auto"
    elif "qwen" in model_id_lower:
        model_kwargs["torch_dtype"] = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    elif "gemma" in model_id_lower:
        print(f"Applying optimized settings for Gemma model: {model_id}")
        target_dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
        quant_config = BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_quant_type="nf4",
                bnb_4bit_compute_dtype=target_dtype,
                bnb_4bit_use_double_quant=True,
        )
        
        model_kwargs = {
            "device_map": "auto",                
            "trust_remote_code": True,
            "low_cpu_mem_usage": True,           
            "quantization_config": quant_config, 
            "torch_dtype": target_dtype,         
        }

    else:
        model_kwargs["torch_dtype"] = torch.float16
    
    if "phi" in model_id_lower or "qwen" in model_id_lower:
        try:                
            print(f"Attempting to set 'flash_attention_2' for {model_id}")
            model_kwargs["attn_implementation"] = "flash_attention_2"
            print(f"{model_id}: Set to use 'flash_attention_2'.")
        except ImportError:
            print(f"{model_id}: 'flash_attention_2' setup failed. Using default.")
            model_kwargs["attn_implementation"] = "sdpa" 
    
    ModelClass = AutoModelForCausalLM
    try:
        print(f"Loading model '{model_id}' with kwargs: {model_kwargs}")
        model = ModelClass.from_pretrained(model_id, **model_kwargs)
        print(f"{model_id} loaded successfully.")
    except Exception as e1:
        print(f"Error loading model {model_id} with primary kwargs: {e1}")
        if "attn_implementation" in model_kwargs and model_kwargs["attn_implementation"] != "sdpa":
            original_attn = model_kwargs.pop("attn_implementation")
            print(f"Retrying without '{original_attn}', falling back to 'sdpa'...")
            model_kwargs["attn_implementation"] = "sdpa" 
            try:
                model = ModelClass.from_pretrained(model_id, **model_kwargs)
                print(f"{model_id} loaded successfully on retry with sdpa.")
            except Exception as e2:
                print(f"Retry with 'sdpa' failed: {e2}")
                print("Trying with minimal kwargs...")
                minimal_kwargs = {
                    "trust_remote_code": True,
                    "device_map": "auto",
                }
                
                if "torch_dtype" in model_kwargs:
                    minimal_kwargs["torch_dtype"] = model_kwargs["torch_dtype"]
                if "quantization_config" in model_kwargs:
                    minimal_kwargs["quantization_config"] = model_kwargs["quantization_config"]
                if "low_cpu_mem_usage" in model_kwargs:
                    minimal_kwargs["low_cpu_mem_usage"] = model_kwargs["low_cpu_mem_usage"]

                try:
                    print(f"Retrying with minimal_kwargs: {minimal_kwargs}")
                    model = ModelClass.from_pretrained(model_id, **minimal_kwargs)
                    print(f"{model_id} loaded successfully with minimal kwargs.")
                except Exception as e_minimal:
                    print(f"CRITICAL: Model loading failed with all fallbacks for {model_id}: {e_minimal}")
                    raise
        else:
            print(f"CRITICAL: Model loading failed, no attention implementation fallbacks for {model_id}.")
            raise e1
    
    if hasattr(model.config, 'pad_token_id') and model.config.pad_token_id is None and tokenizer.pad_token_id is not None:
        model.config.pad_token_id = tokenizer.pad_token_id
        print(f"Model pad_token_id was None, set to tokenizer's pad_token_id: {model.config.pad_token_id}")

    if not getattr(model.config, "chat_template", None) and not getattr(tokenizer, "chat_template", None):        
        print(f"[WARN] Model {model_id}: No chat_template found. Manual prompting may be needed.")      

    model.eval()
    if hasattr(model.config, 'use_cache'):
        model.config.use_cache = True    
    print(f"Model '{model_id}' and its tokenizer are ready.")
    return model, tokenizer


# --- 3. Prompt ---
def make_classification_prompt_messages(dialogue_info, utterance_id_for_output, reasoning_text):  
    system_prompt = f"""
    You are an expert in analyzing utterance contributions in problem-solving discussions. Your task is to perform two steps:

    IMPORTANT NOTE ABOUT UTTERANCE CONTENT:
    - Content within parentheses () or square brackets [] represents ACTIONS/BEHAVIORS, not speech.
    - Example: "[points to the board]", "(writes on paper)", "[moves blocks]" are actions, not verbal utterances.
    - If an utterance consists entirely of action descriptions with no speech, classify it as Uncorrelated (UC).

    STEP 1: REASONING
    Analyze the utterance based on the rules below. BRIEFLY explain your reasoning (1-2 concise sentences) on its contribution to idea development.
    Example: Reasoning: Speaker explains their method of adding 10s, fitting EXP criteria as it details their reasoning.

    STEP 2: CLASSIFICATION OUTPUT
    Provide the classification as a SINGLE line: "FINAL_CLASSIFICATION: [UTTERANCE_ID] : [NAME] : [LABEL] : [REFERENCE]"
    - EXP & UC: [REFERENCE] is 'NA'.
    - EOI: [REFERENCE] is the NAME of the participant whose idea is engaged (trace back if needed). Use 'Previous Speaker' if name is unknown but clearly refers to t-1 idea.

    --- DECISION FLOW ---
    Follow this order strictly:
    1.  Check for EOI (Engage Others Idea) first. Does the utterance DIRECTLY respond to, critique, correct, or question a specific, conceptual idea from a peer? If YES, classify as EOI and determine the level (LOW, MEDIUM, HIGH).
    2.  If not EOI, check for EXP (Explain Own Idea). Is the speaker verbalizing their own conceptual reasoning, strategy, or the 'why' behind their actions? If YES, classify as EXP.
    3.  If not EOI or EXP, classify as UC (Uncorrelated). This is the default for anything that lacks clear conceptual contribution.

    --- CRITICAL WARNING: AVOID COMMON MISTAKES ---
    - UC vs. EOI(LOW): A simple "Yes", "No", "I agree", or "Wow!" is NOT EOI. It is Uncorrelated (UC) unless it clearly rephrases the peer's conceptual idea, proving understanding. Social agreement alone is not conceptual engagement.
    - UC vs. EXP: Simply describing an action ("I'm counting") or stating an answer ("It's 35") is Uncorrelated (UC). To be EXP, the speaker must explain the purpose of the action ("I'm counting to check my answer") or the reasoning behind the answer ("It's 35 because 70 divided by 2 is 35").

    --- CATEGORY DEFINITIONS & CRITERIA ---

    1.  Explain Own Idea (EXP):
        -   Definition: Speaker verbalizes their own conceptual reasoning, mathematical strategy, or understanding with clear explanation, justification, or elaboration that reveals their thought process. This includes explanations of the speaker's own ideas or actions, even if prompted by a peer's question.
        -   Key Includes:
            *   Elaborating a novel strategy or a significant modification to an existing one.
            *   Explaining a conceptual realization with its basis.
            *   Justifying a mathematical method or answer.
            *   Articulating a step-by-step conceptual plan or calculation process with its underlying logic.

    2.  Engage Others Idea (EOI): Speaker directly engages with the content of another's specific articulated conceptual mathematical idea. The level depends on the depth and nature of this engagement.

        -   EOI(LOW): Minimum Conceptual Engagement - Confirmation & Basic Clarification
            *   Definition: Speaker briefly acknowledges, confirms, agrees/disagrees with, or asks a very simple, direct question about a clearly identifiable, specific conceptual mathematical point previously articulated by a peer. The utterance MUST demonstrate BOTH (1) clear understanding of that specific conceptual point AND (2) make a direct, unambiguous verbal reference to it.
            *   Key Indicators: Confirmatory Restatement, Targeted Agreement/Disagree-ment, Simple clarification on a specific detail within the peer's idea.

        -   EOI(MEDIUM): Probing & Minor Elaboration (of a peer's idea)
            *   Definition: Speaker seeks to deepen their understanding of a peer's specific conceptual idea by asking questions that probe the underlying reasoning, assumptions, or implications of that peer's idea. They might also restate the peer's idea with minor conceptual additions or offer small, scaffolded extensions.
            *   Key Indicators: Probing "Why" or "How" Questions about a peer's reasoning, Requesting Elaboration on a peer's idea, Identifying Ambiguity for clarification within a peer's idea.

        -   EOI(HIGH): Critique, Significant Extension, & Synthesis (of a peer's idea)
            *   Definition: Speaker critically evaluates a peer's specific conceptual idea by offering a reasoned critique, proposing a significant and justified alternative/refinement to that peer's idea, or by synthesizing it with other ideas to create a more robust solution. This involves substantial conceptual work.
            *   Clarification on Critique: A critique must be reasoned. A simple, unelaborated disagreement or correction (e.g., 'No, the answer is 20') does not qualify as EOI(HIGH). It is a targeted disagreement about a conceptual point but lacks justification, making it EOI(LOW). To be EOI(HIGH), the utterance must explain why the peer's idea is incorrect (e.g., 'No, it's 20, because you forgot to add the 2.'), or clearly justify their disagreement by demonstrating their own correct reasoning or solution process (verbally or through action) in a manner that implicitly highlights the peer's error in relation to their original idea.
            *   Key Indicators: Reasoned Conceptual Critique of a peer's idea, Correction with Justification related to a peer's error, Proposing Justified Alternatives to a peer's idea, Conceptual Synthesis of a peer's idea with others.
            *   Proposing a Conceptual Paradigm Shift: This applies when a speaker clearly rejects a peer's more concrete, lower-level strategy and proposes a shift to a much more abstract or higher-level conceptual category. In this case, even if the proposed alternative does not include a specific methodology, the 'leap' itself is considered a significant critique and proposal that fundamentally changes the direction of problem-solving.

    3.  Uncorrelated (UC):
        -   Definition: No meaningful or discernible conceptual mathematical contribution; utterance is vague, off-task, purely procedural without explanation, or a brief unelaborated realization/intention.
        -   Key Includes:
            *   Narration of one's own actions without explaining the conceptual purpose.
            *   Vague statements ("This is hard," "I'm confused" without specifying the conceptual point).
            *   Simple affirmations/negations ("Yes", "I agree", "Okay") without specific reference to a peer's conceptual idea and demonstrating understanding of it.
            *   Generic procedural questions/statements ("What's next?").
            *   Unelaborated realizations ("I get it!", "I know!", "Oh!").
            *   Stating answers or numbers without explaining the process or reasoning.
            *   Reading aloud from a worksheet or simply repeating a peer's words without adding conceptual value.
            *   Brief self-corrections ('Oops') without explaining the conceptual reason for the correction.

    --- CORE CLASSIFICATION PRINCIPLES ---
    1. Conceptual Contribution Focus: Your primary focus is on conceptual idea development in mathematics.
    2. EOI - Engaging a Peer's Conceptual Idea: EOI requires engagement with a specific peer's conceptual mathematical idea, not just their words or a surface-level answer.
    3. EXP - Explaining Own Conceptual Reasoning: EXP requires explaining one's own reasoning, strategy, or understanding with clear justification or elaboration.
    4. Priority for Primary Conceptual Function: Choose the category that best reflects the utterance's dominant conceptual purpose. In complex cases where functions are mixed, use the Tie-Breaker rules below to help determine this primary function.
    5. UC as Default, with Caution for EOI(LOW): If an utterance does not clearly meet the criteria for EXP or EOI, classify it as UC. However, do not default to UC too aggressively if it meets the minimum criteria for EOI(LOW).
    6. Context is Key: Your classification must be based on the flow of the dialogue. Look beyond the immediate previous utterance; trace back to the origin of an idea for accurate EOI referencing or to understand the full context for an EXP.
    7. The "Target of Reasoning" Principle (EOI Precedence Rule): If an utterance's primary conceptual function is to respond directly to, critique, correct, or build upon a specific peer's articulated idea, it MUST be classified as EOI.
        - This is a strict priority rule. It holds true even if the speaker explains their own reasoning or calculation process as the means for that critique or extension. The target of the idea (a peer) takes precedence over the form of the reasoning (one's own calculation).
        - Critical Example (Correction as EOI(HIGH)):
            Peer A: "I got 18."
            Speaker B: "No, 9 plus 9 is 18, but you forgot to add the 2, so it's 20."
            Correct Classification: EOI(HIGH) : Peer A. This is NOT EXP. Although Speaker B explains their own calculation, the entire purpose of the utterance is to correct Peer A's idea.
    8. Principle of Conceptual Impact Over Explicit Explanation:
        - Do not automatically classify an utterance as UC just because it lacks an explicit "because" clause. Evaluate its function within the dialogue.
        - The Test: Does the utterance introduce a new, relevant mathematical object, operation, or logical step into the conversation? If yes, it likely has conceptual value.
            - Lean towards UC if it's just stating a number without context. (e.g., Peer A: "This is hard." Speaker B: "70.")
            - Lean towards EXP or EOI if it introduces a key operation or a logical next step based on the current context. (e.g., After the group agrees the total is 70 -> Speaker B: "Okay, so 70 divided by 2.") This utterance, despite its brevity, introduces the crucial next conceptual step (division) and is therefore not UC.
    9. Principle of Utterance Continuity: If an utterance is a direct continuation of the speaker's own previous turn (e.g., finishing a sentence or elaborating on a point immediately after pausing), evaluate the current utterance in the context of the combined statement. The classification should reflect the conceptual contribution of the complete idea, not just the final fragment.

    --- TIE-BREAKER RULES FOR BORDERLINE CASES ---
    The following are priority principles to increase consistency when classifying ambiguous, borderline cases.

    1. (EOI vs. EXP) The "Function over Form" Rule (Highest Priority):
    - This rule takes precedence over all others when an utterance has mixed characteristics. It applies when an utterance contains the speaker's own reasoning or calculation (form of EXP) but is used to directly critique, correct, or offer a counter-proposal to a peer's specific idea (function of EOI).
    - The Test: Ask, "What is the primary purpose of this utterance in the dialogue?"
        - If the purpose is to correct a peer's error, challenge a peer's method, or propose an alternative in direct response to a peer, it MUST be classified as EOI(HIGH). The corrective/critical function outweighs the explanatory form.
    - Critical Failure Case to Avoid:
        - Peer A: "I got the wrong answer, 18."
        - Speaker B: "No, because 9 plus 9 is 18, but you forgot to add the 2, so the answer is 20."
        - Correct Classification: Engage Others Idea (HIGH) : Peer A.
        - Incorrect Classification: Explain Own Idea : NA. Do not classify this as EXP simply because Speaker B explains their own calculation. The entire utterance exists only because of Peer A's mistake and its primary function is to correct it.

    2. (UC vs. EOI(LOW)) The "Rephrasing vs. Repeating" Rule:
    - An utterance that simply repeats a key word (e.g., "multiplication") or number from a peer should lean towards UC. This is because it provides insufficient evidence of conceptual understanding.
    - Conversely, classify as EOI(LOW) if the speaker rephrases the peer's idea in their own words (even slightly) or includes a specific result based on that idea (e.g., "Oh, so you mean 3 times 4 is 12"). This proves the speaker actively processed the idea.
    - The Test: Did the speaker parrot the peer's idea, or did they digest and explain it in their own head? Only the latter qualifies as EOI(LOW).

    3. (UC vs. EXP) The "Describing Actions vs. Explaining Purpose" Rule:
    - Simply describing an action ("I'm grouping these by 10s") is UC.
    - Explaining the conceptual purpose or reason (the 'Why') behind the action makes it EXP (e.g., "I'm grouping these by 10s to make them easier to count later").
    - Clarification on "Purpose": Explaining how a mathematical strategy is being constructed or how one is modeling the problem's components is also considered "explaining the purpose." The "why" is inherent in the strategic choice of representation.
        - Example of Conceptual Modeling (EXP): "So I'm putting 70 blocks here, and I'm making two groups, to show the total for the two days."
        - This is EXP because it explains how the actions (making groups, using 70 blocks) map onto the concepts of the problem (two days, total).

    4. (EXP vs. EOI(HIGH)) The "Foundation vs. Spark" Rule (for judging idea ownership):
    - To decide, ask this question: "Without the peer's idea, could the speaker's idea still stand on its own?"
    - EOI(HIGH) (Foundation Principle): This applies when the peer's idea serves as the 'foundation' for the speaker's idea. The speaker is modifying, critiquing, or extending the peer's idea, and without it, the speaker's utterance would lose its meaning.
    - EXP (Spark Principle): This applies when the peer's idea only served as a 'spark' for the speaker to come up with a conceptually independent idea. The speaker's idea would still stand as a complete strategy on its own.

    5. (EOI(LOW) vs. EOI(MEDIUM)) The "New vs. Implied Information" Test:
    - Lean towards EOI(LOW): if the utterance primarily confirms or rephrases information that was already stated or clearly implied by the peer. It demonstrates understanding of the existing idea. (e.g., Peer: "We need to split 70 in half." Speaker: "Oh, so 70 divided by 2.")
    - Lean towards EOI(MEDIUM): if the utterance adds a new, explicit piece of conceptual information (like a label, context, or reason) that was not present in the peer's original statement. It enriches the existing idea. (e.g., Peer: "We need to use the 2." Speaker: "Right, because the 2 represents the days.")
    """

    user_prompt = f"""
    Your task:
    Using the rules from the system prompt, classify the utterance with ID {utterance_id_for_output}. First give a brief reasoning, then provide a single line classification in the required format.

    Your response must include:
    1. A concise reasoning (STEP 1)
    2. One strict "FINAL_CLASSIFICATION:" line (STEP 2)
    
    Output format examples:
    Reasoning: Speaker explains own detailed method for grouping and multiplying.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Julian : Explain Own Idea : NA

    Reasoning: Speaker asks "Why did you decide to multiply there?" about John's specific step in his solution.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Julian : Engage Others Idea (MEDIUM) : John

    Reasoning: Speaker is just counting aloud "1, 2, 3" while moving blocks, no explanation of the conceptual plan.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Delilah : Uncorrelated : NA

    Reasoning: Peer A: "I think the pattern is adding 3 each time." Speaker B: "Yes, I see that too, it's adding 3." This shows understanding of and agreement with Peer A's specific conceptual pattern.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Keila : Engage Others Idea (LOW) : Peer A

    Reasoning: Peer A: "The answer is 12." Speaker B: "I agree." This is a generic agreement without referencing the conceptual method or reasoning of Peer A.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Keila : Uncorrelated : NA   

    Reasoning: Peer A states, "The result is 45." Speaker B says, "No, it's 50." This is a direct refutation of a peer's conceptual point (the result) but provides no reasoning or justification, qualifying it as low-level engagement.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Kenji : Engage Others Idea (LOW) : Peer A

    Reasoning: Speaker's utterance "...so we divide by two" completes their thought from their previous utterance "To find the amount for one day...". The combined idea explains the strategy of dividing by two to find the daily amount, making it EXP.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Sarah : Explain Own Idea : NA

    Reasoning: Speaker states "I know how to solve this now!" but doesn't explain the method or what they realized conceptually.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Alex : Uncorrelated : NA

    Reasoning: Speaker critiques Chris's method: "Your addition is correct, but multiplying 5 by 3 would be a more direct conceptual approach here."
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Ben : Engage Others Idea (HIGH) : Chris

    Reasoning: Speaker says "Okay, let's start problem 2." This is procedural coordination.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Maria : Uncorrelated : NA

    Reasoning: Speaker asks a standalone "What?" after a peer's long explanation, without indicating what part is unclear.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : David : Uncorrelated : NA

    Reasoning: Peer C: "So we need to find the total area." Speaker D: "So, by 'total area', you mean we should multiply length by width for each rectangle?" This clarifies understanding of the peer's specific conceptual goal.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Chloe : Engage Others Idea (LOW) : Peer C

    Reasoning: Speaker explains their realization: "Ah, now I understand! 'Each' means we need to perform the operation for every single item, not just once for the total." This explains what was understood conceptually.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Sam : Explain Own Idea : NA

    Reasoning: Speaker says "My strategy is to use division here." but does not explain why division is appropriate or how it will be applied conceptually.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Taylor : Uncorrelated : NA

    Reasoning: Speaker shows their work and explains the strategy's purpose, "See, I made 5 groups of 3. This way, we can multiply 5 by 3 to get the total number of items needed for all 5 days."
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Riley : Explain Own Idea : NA

    Reasoning: Peer A: "The answer is 12." Speaker B: "I disagree with you cause i got 2, 3,... 10." This directly critiques Peer A's conceptual premise (using '10') and provides a correction, making it EOI(HIGH) even though it explains the speaker's own reasoning for the critique.
    FINAL_CLASSIFICATION: {utterance_id_for_output} : Speaker B : Engage Others Idea (HIGH) : Peer A
    
    Context:
    - Block Index: {dialogue_info.get("current_block_index", "N/A")}
    - Group: {dialogue_info.get("current_group", "N/A")}
    - Speaker: {dialogue_info.get("current_speaker", "N/A")}
    - Context Description: {dialogue_info.get("context_description", "N/A")}

    Previous Utterances:
    - t-2 ({dialogue_info.get("previous_speaker_2", "N/A")}): {dialogue_info.get("previous_utterance_2", "None")}
    - t-1 ({dialogue_info.get("previous_speaker_1", "N/A")}): {dialogue_info.get("previous_utterance_1", "None")}

    Current Utterance to Classify (ID: {utterance_id_for_output}):
    - Speaker: {dialogue_info.get("current_speaker", "N/A")}
    - Text: "{dialogue_info.get("current_utterance_text", "")}"

    Classification result:
    Reasoning: {reasoning_text}    
    FINAL_CLASSIFICATION: """

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]
    return messages

# --- 4. logit calculation ---
@torch.no_grad()
def calculate_token_probabilities_only(model, tokenizer, dialogue_info, utterance_id_for_output, reasoning_text, model_id="unknown"):
    """Calculate token probabilities using existing reasoning text"""
    
    # Step 1: Generate classification using existing reasoning
    classification_messages = make_classification_prompt_messages(dialogue_info, utterance_id_for_output, reasoning_text)
    
    try:
        classification_prompt_for_model = tokenizer.apply_chat_template(
            classification_messages, tokenize=False, add_generation_prompt=True, enable_thinking=False
        )
        # No additional FINAL_CLASSIFICATION needed since it's already in the user prompt

    except Exception as e:
        print(f"Warning: tokenizer.apply_chat_template failed for classification: {e}. Using manual concatenation.")
        # Similar fallback logic as reasoning step
        classification_prompt_for_model = ""
        system_content = ""
        user_content = ""

        for msg in classification_messages:
            if msg['role'] == 'system':
                system_content = msg['content']
            elif msg['role'] == 'user':
                user_content = msg['content']

        combined_user_content = user_content
        if system_content:
            combined_user_content = f"SYSTEM INSTRUCTIONS:\n{system_content}\n\nUSER TASK:\n{user_content}"

        if "gemma" in model_id.lower():
            classification_prompt_for_model = tokenizer.bos_token if tokenizer.bos_token else ""
            classification_prompt_for_model += f"<start_of_turn>user\n{combined_user_content}<end_of_turn>\n"
            classification_prompt_for_model += f"<start_of_turn>model\n"
        elif "qwen" in model_id.lower():
            classification_prompt_for_model = f"<|im_start|>system\n{system_content}<|im_end|>\n" if system_content else ""
            classification_prompt_for_model += f"<|im_start|>user\n{user_content}<|im_end|>\n<|im_start|>assistant\n"
        elif "llama-3" in model_id.lower():
            classification_prompt_for_model = tokenizer.bos_token if tokenizer.bos_token else ""
            for msg in classification_messages:
                start_header = getattr(tokenizer, 'special_tokens_map', {}).get('<|start_header_id|>', '<|start_header_id|>')
                end_header = getattr(tokenizer, 'special_tokens_map', {}).get('<|end_header_id|>', '<|end_header_id|>')
                eot = getattr(tokenizer, 'special_tokens_map', {}).get('<|eot_id|>', '<|eot_id|>')
                classification_prompt_for_model += f"{start_header}{msg['role']}{end_header}\n\n{msg['content']}{eot}"
            classification_prompt_for_model += f"{start_header}assistant{end_header}\n\n"
        elif "phi" in model_id.lower():
            classification_prompt_for_model = f"<|user|>\n{combined_user_content}<|end|>\n<|assistant|>\n"
        else:
            classification_prompt_for_model = f"System: {system_content}\n" if system_content else ""
            classification_prompt_for_model += f"User: {user_content}\nAssistant:\n"

    # Prepare classification inputs for logit calculation only
    model_max_len = tokenizer.model_max_length or 8192
    context_len_budget = max(64, model_max_len - 100)  # No need for generation budget
    classification_inputs = tokenizer(classification_prompt_for_model, return_tensors="pt", padding="longest", truncation=True, max_length=context_len_budget)
    
    # No generation needed - just calculate probabilities directly
    # Create a dummy classification line for consistency
    current_id_str = str(utterance_id_for_output).strip()
    speaker_name = dialogue_info.get('current_speaker', 'Speaker')
    final_output_line = f"{current_id_str} : {speaker_name} : LOGIT_CALCULATION_ONLY : NA"
    
    print(f"Calculating logits for ID {utterance_id_for_output} using existing reasoning (no generation needed)")

    classification_labels = [
        "Explain Own Idea",
        "Engage Others Idea (LOW)",
        "Engage Others Idea (MEDIUM)", 
        "Engage Others Idea (HIGH)",
        "Uncorrelated"
    ]
    
    speaker_name = dialogue_info.get('current_speaker', 'Speaker')
        
    reference_for_logits = "Peer"  
    try:
        parts_for_ref = final_output_line.split(' : ')
        if len(parts_for_ref) >= 4:
            predicted_ref = parts_for_ref[3].strip()
            if predicted_ref and predicted_ref.upper() != "NA":
                reference_for_logits = predicted_ref
    except Exception as e:
        print(f"DEBUG: Failed to parse reference from classification line: {e}")

    if reference_for_logits == "Peer":
        if 'previous_speaker_1' in dialogue_info and dialogue_info.get('previous_speaker_1') and dialogue_info['previous_speaker_1'] != speaker_name:
            reference_for_logits = dialogue_info['previous_speaker_1']

    print(f"DEBUG: Using reference '{reference_for_logits}' for all EOI logit calculations")
    
    possible_classifications = {}
    current_id_str = str(utterance_id_for_output).strip()

    for label in classification_labels:
        if "Engage Others Idea" in label:
            classification_line = f" {current_id_str} : {speaker_name} : {label} : {reference_for_logits}"
        else:
            classification_line = f" {current_id_str} : {speaker_name} : {label} : NA"
        
        possible_classifications[label] = classification_line

    # Calculate log probabilities
    classification_logits = {}
    with torch.no_grad():
        for label, classification_line in possible_classifications.items():
            full_sequence = classification_prompt_for_model + classification_line
            try:
                full_inputs = tokenizer(full_sequence, return_tensors="pt", truncation=True, max_length=context_len_budget)
                outputs = model(
                    input_ids=full_inputs["input_ids"].to(model.device),
                    attention_mask=full_inputs["attention_mask"].to(model.device)
                )
                prompt_length = classification_inputs["input_ids"].shape[1]
                classification_token_ids = full_inputs["input_ids"][0, prompt_length:]
                
                if len(classification_token_ids) > 0:
                    classification_logits_tensor = outputs.logits[0, prompt_length-1:prompt_length-1+len(classification_token_ids), :]
                    log_probs = torch.log_softmax(classification_logits_tensor, dim=-1)
                    total_log_prob = sum(log_probs[i, token_id].item() for i, token_id in enumerate(classification_token_ids) if i < log_probs.shape[0])
                    classification_logits[label] = total_log_prob
                    print(f"DEBUG: Label '{label}' -> sequence log_prob: {total_log_prob:.4f}")
                else:
                    classification_logits[label] = float('-inf')
                    print(f"DEBUG: Label '{label}' -> no tokens to evaluate")
            except Exception as e:
                print(f"  [WARN] Error calculating sequence probability for {label}: {e}")
                classification_logits[label] = float('-inf')
    
    print(f"DEBUG: Raw sequence-based logits: {classification_logits}")
    
    # Softmax normalization
    valid_logits = [(k, v) for k, v in classification_logits.items() if v != float('-inf')]
    if valid_logits:
        logit_values = [v for k, v in valid_logits]
        logit_tensor = torch.tensor(logit_values)
        log_probs_normalized = torch.log_softmax(logit_tensor, dim=0)
        probs = torch.softmax(logit_tensor, dim=0)
        
        print("DEBUG: Normalized sequence-based logits (CSV column mapping):")
        for i, (label, _) in enumerate(valid_logits):
            classification_logits[label] = log_probs_normalized[i].item()
            # Map to CSV column names
            if label == 'Explain Own Idea':
                csv_col = 'logit_explain_own_idea'
            elif label == 'Engage Others Idea (LOW)':
                csv_col = 'logit_engage_others_low'
            elif label == 'Engage Others Idea (MEDIUM)':
                csv_col = 'logit_engage_others_medium'
            elif label == 'Engage Others Idea (HIGH)':
                csv_col = 'logit_engage_others_high'
            elif label == 'Uncorrelated':
                csv_col = 'logit_uncorrelated'
            else:
                csv_col = 'unknown'
            print(f"  '{label}' -> log_prob: {log_probs_normalized[i].item():.4f}, prob: {probs[i].item():.4f} -> {csv_col}")
        
        for label in classification_labels:
            if label not in dict(valid_logits):
                classification_logits[label] = -1000.0
    
    try:        
        classification_prefix = classification_prompt_for_model + f" {current_id_str} : {speaker_name} :"
        prefix_inputs = tokenizer(classification_prefix, return_tensors="pt", truncation=True, max_length=context_len_budget)
        with torch.no_grad():
            outputs_prefix = model(
                input_ids=prefix_inputs["input_ids"].to(model.device),
                attention_mask=prefix_inputs["attention_mask"].to(model.device),
                use_cache=False 
            )
        logits_next = outputs_prefix.logits[0, -1]
        probs_next = torch.softmax(logits_next, dim=-1)

        label_first_tokens = {
            "Explain Own Idea": " Explain",
            "Engage Others Idea": " Engage",
            "Uncorrelated": " Uncorrelated"
        }
        for lbl, tok_txt in label_first_tokens.items():
            tok_ids = tokenizer.encode(tok_txt, add_special_tokens=False)
            if tok_ids:
                classification_logits[f"token_prob_{lbl.lower().replace(' ', '_').replace('(', '').replace(')', '')}"] = probs_next[tok_ids[0]].item()

        engage_prefix = classification_prefix + " Engage Others Idea ("
        engage_inputs = tokenizer(engage_prefix, return_tensors="pt", truncation=True, max_length=context_len_budget)
        with torch.no_grad():
            outputs_engage = model(
                input_ids=engage_inputs["input_ids"].to(model.device),
                attention_mask=engage_inputs["attention_mask"].to(model.device),
                use_cache=False
            )
        logits_engage_next = outputs_engage.logits[0, -1]
        probs_engage_next = torch.softmax(logits_engage_next, dim=-1)
        for lvl in ["LOW", "MEDIUM", "HIGH"]:
            tok_id_lvl = tokenizer.encode(lvl, add_special_tokens=False)
            if tok_id_lvl:
                classification_logits[f"token_prob_engage_{lvl.lower()}"] = probs_engage_next[tok_id_lvl[0]].item()
        
        print("DEBUG next-token probs (CSV column mapping):")
        print(f"  EXP:{classification_logits.get('token_prob_explain_own_idea', float('nan')):.4f} -> tokprob_explain_own_idea")
        print(f"  EOI:{classification_logits.get('token_prob_engage_others_idea', float('nan')):.4f} -> tokprob_engage_others")
        print(f"  UC:{classification_logits.get('token_prob_uncorrelated', float('nan')):.4f} -> tokprob_uncorrelated")
        print(f"  EOI-L:{classification_logits.get('token_prob_engage_low', float('nan')):.4f} -> tokprob_engage_low")
        print(f"  EOI-M:{classification_logits.get('token_prob_engage_medium', float('nan')):.4f} -> tokprob_engage_medium")
        print(f"  EOI-H:{classification_logits.get('token_prob_engage_high', float('nan')):.4f} -> tokprob_engage_high")
    except Exception as e:
        print(f"[WARN] Next-token label prob calculation failed: {e}")
    
    return final_output_line, reasoning_text, classification_logits



# --- 5. main function ---
def process_dialogue_dataframe_with_existing_reasoning(df_with_reasoning, model, tokenizer, model_id="unknown"):
    """Process dialogue dataframe using existing reasoning from CSV file"""
    results = []
    
    # Sort by group, date, and block_index to ensure proper ordering
    # df_sorted = df_with_reasoning.sort_values(['group', 'date', 'block_index', 'utterance_id']).reset_index(drop=True)
    df_sorted = df_with_reasoning
    for index, row in tqdm(df_sorted.iterrows(), total=len(df_sorted), desc="Processing Token Probabilities"):
        current_utterance_id = str(row['utterance_id']) 
        current_group = str(row.get('group', "UnknownGroup"))
        current_date_str = str(row.get('date', "UnknownDate")) 
        current_timestamp_str = str(row.get('timestamp', "N/A"))
        current_block_index = row.get('block_index', 1)
        
        current_speaker = str(row.get('name', "UnknownSpeaker"))
        current_utterance_text = str(row.get('utterance', ""))
        existing_reasoning = clean_reasoning_text(str(row.get('llm_reasoning', "")))
        
        # Build dialogue context with previous utterances from same group/date/block
        dialogue_info = {
            "current_block_index": current_block_index,
            "current_group": current_group,
            "current_date": current_date_str, 
            "current_speaker": current_speaker,
            "current_utterance_text": current_utterance_text,
            "current_utterance_indent": 0
        }
        
        # Find previous utterances in the same group, date, and block
        same_context_mask = (
            (df_sorted['group'] == current_group) & 
            (df_sorted['date'] == current_date_str) & 
            (df_sorted['block_index'] == current_block_index) &
            (df_sorted.index < index)  # Only consider previous utterances
        )
        previous_utterances = df_sorted[same_context_mask].tail(3)  # Get up to 3 previous utterances
        
        if len(previous_utterances) >= 1:
            prev_1 = previous_utterances.iloc[-1]
            dialogue_info["previous_utterance_1"] = str(prev_1.get('utterance', 'N/A'))
            dialogue_info["previous_speaker_1"] = str(prev_1.get('name', 'N/A'))
        else:
            dialogue_info["previous_utterance_1"] = "N/A"
            dialogue_info["previous_speaker_1"] = "N/A"
            
        if len(previous_utterances) >= 2:
            prev_2 = previous_utterances.iloc[-2]
            dialogue_info["previous_utterance_2"] = str(prev_2.get('utterance', 'N/A'))
            dialogue_info["previous_speaker_2"] = str(prev_2.get('name', 'N/A'))
        else:
            dialogue_info["previous_utterance_2"] = "N/A"
            dialogue_info["previous_speaker_2"] = "N/A"
            
        if len(previous_utterances) >= 3:
            prev_3 = previous_utterances.iloc[-3]
            dialogue_info["previous_utterance_3"] = str(prev_3.get('utterance', 'N/A'))
            dialogue_info["previous_speaker_3"] = str(prev_3.get('name', 'N/A'))
        else:
            dialogue_info["previous_utterance_3"] = "N/A"
            dialogue_info["previous_speaker_3"] = "N/A"
        
        classification_result_line = f"{current_utterance_id} : {current_speaker} : CLASSIFICATION_FAILED : NA"
        reasoning_text = existing_reasoning
        classification_logits = {}
        
        if not current_utterance_text.strip() or not existing_reasoning.strip():
            classification_result_line = f"{current_utterance_id} : {current_speaker} : Uncorrelated : NA"
            reasoning_text = existing_reasoning if existing_reasoning.strip() else "Empty utterance or reasoning"
            # Set default logits for empty utterance
            classification_logits = {
                "Explain Own Idea": float('-inf'),
                "Engage Others Idea (LOW)": float('-inf'),
                "Engage Others Idea (MEDIUM)": float('-inf'),
                "Engage Others Idea (HIGH)": float('-inf'),
                "Uncorrelated": 0.0  # Give highest logit to Uncorrelated for empty utterances
            }
        else:
            try:
                classification_result_line, reasoning_text, classification_logits = calculate_token_probabilities_only(
                    model, tokenizer, dialogue_info, current_utterance_id, existing_reasoning, model_id=model_id
                )
            except Exception as e:
                print(f"  [CRITICAL ERROR] Token probability calculation failed for utterance ID {current_utterance_id}: '{current_utterance_text[:50]}...' - {e}")
                import traceback; traceback.print_exc()
                reasoning_text = existing_reasoning
                # Set default error logits
                classification_logits = {
                    "Explain Own Idea": float('-inf'),
                    "Engage Others Idea (LOW)": float('-inf'),
                    "Engage Others Idea (MEDIUM)": float('-inf'),
                    "Engage Others Idea (HIGH)": float('-inf'),
                    "Uncorrelated": float('-inf')
                }
        
        # Copy existing data and add new logit information
        result_row = row.to_dict()
        
        # Remove unnecessary parsed_* columns if they exist
        columns_to_remove = [col for col in result_row.keys() if col.startswith('parsed_')]
        for col in columns_to_remove:
            result_row.pop(col, None)
        
        result_row.update({
            'llm_classification_output_line_new': classification_result_line,
            'logit_explain_own_idea': classification_logits.get('Explain Own Idea', float('-inf')),
            'logit_engage_others_low': classification_logits.get('Engage Others Idea (LOW)', float('-inf')),
            'logit_engage_others_medium': classification_logits.get('Engage Others Idea (MEDIUM)', float('-inf')),
            'logit_engage_others_high': classification_logits.get('Engage Others Idea (HIGH)', float('-inf')),
            'logit_uncorrelated': classification_logits.get('Uncorrelated', float('-inf')),
            # --- next-token probs ---
            'tokprob_explain_own_idea': classification_logits.get('token_prob_explain_own_idea', np.nan),
            'tokprob_engage_others': classification_logits.get('token_prob_engage_others_idea', np.nan),
            'tokprob_uncorrelated': classification_logits.get('token_prob_uncorrelated', np.nan),
            'tokprob_engage_low': classification_logits.get('token_prob_engage_low', np.nan),
            'tokprob_engage_medium': classification_logits.get('token_prob_engage_medium', np.nan),
            'tokprob_engage_high': classification_logits.get('token_prob_engage_high', np.nan)
        })
        
        results.append(result_row)
            
        if (index + 1) % 20 == 0: 
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
    
    if torch.cuda.is_available(): 
        torch.cuda.empty_cache()

    return pd.DataFrame(results)

# --- 6. LLM output parsing ---
def parse_llm_output_line(line_str, expected_id_str):
    parts = line_str.split(' : ')
    if len(parts) == 4:
        parsed_id = parts[0].strip()
        parsed_name = parts[1].strip()
        llm_label_full = parts[2].strip() 
        llm_reference = parts[3].strip()

        llm_label_main = llm_label_full
        llm_engagement = "NA" 

        if "Engage Others Idea" in llm_label_full:
            if "(LOW)" in llm_label_full:
                llm_label_main = "Engage Others Idea"
                llm_engagement = "LOW"
            elif "(MEDIUM)" in llm_label_full:
                llm_label_main = "Engage Others Idea"
                llm_engagement = "MEDIUM"
            elif "(HIGH)" in llm_label_full:
                llm_label_main = "Engage Others Idea"
                llm_engagement = "HIGH"

        result_dict = {
            "parsed_utterance_id": parsed_id,
            "parsed_name": parsed_name,
            "parsed_indent": "0",  # Default value since it's no longer in the input
            "llm_label": llm_label_main,      
            "llm_engagement": llm_engagement, 
            "llm_reference": llm_reference
        }

        if parsed_id == expected_id_str:
            return result_dict
        else:
            print(f"  [PARSE_ID_MISMATCH] Expected ID {expected_id_str} but got {parsed_id} in line: '{line_str}'")
            result_dict["llm_label"] = f"ID_MISMATCH_{llm_label_main}"
            return result_dict

    print(f"  [PARSE_WARN] LLM output line does not have 4 parts. Line: '{line_str}' for ID {expected_id_str} (Found {len(parts)} parts)")
    return {
        "parsed_utterance_id": str(expected_id_str), 
        "parsed_name": "ERR_FORMAT",
        "parsed_indent": "0",  # Default value
        "llm_label": "LINE_FORMAT_ERROR", 
        "llm_engagement": "NA",
        "llm_reference": "NA"
    }

if __name__ == '__main__':     
    parser = argparse.ArgumentParser(description="Calculate token probabilities using existing reasoning from CSV file.")
    parser.add_argument(
        "--model_id", type=str, default="meta-llama/Meta-Llama-3.1-8B-Instruct", 
        help="Hugging Face model ID (e.g., 'meta-llama/Meta-Llama-3.1-8B-Instruct')."
    )
    parser.add_argument("--input_csv", type=str, required=True, help="Input CSV file with existing reasoning (llm_reasoning column).")
    parser.add_argument("--output_csv", type=str, default="classification_results_with_logits.csv", help="Output CSV filename.")

    args = parser.parse_args()   

    start_time = time.time()
    print(f"Using model: {args.model_id}")
    print(f"Input CSV: {args.input_csv}")
    print(f"Output CSV: {args.output_csv}")

    try:
        # Check if input CSV exists
        if not os.path.exists(args.input_csv):
            print(f"Error: Input CSV file '{args.input_csv}' not found.")
            exit(1)
        
        # Load existing CSV with reasoning
        print(f"Loading existing CSV file: {args.input_csv}")
        df_input = pd.read_csv(args.input_csv, encoding='utf-8-sig')
        
        # Validate required columns
        required_columns = ['utterance_id', 'timestamp', 'name', 'utterance', 'group', 'date', 'llm_reasoning']
        missing_columns = [col for col in required_columns if col not in df_input.columns]
        if missing_columns:
            print(f"Error: Missing required columns in CSV: {missing_columns}")
            print(f"Available columns: {list(df_input.columns)}")
            exit(1)
        
        print(f"Successfully loaded CSV with {len(df_input)} utterances")
        print(f"CSV columns: {list(df_input.columns)}")
        
        # Load model and tokenizer
        model, tokenizer = load_model_and_tokenizer(args.model_id)   
        print(model.hf_device_map)
        
        if df_input.empty: 
            print("Input DataFrame is empty. Exiting."); 
            exit()
        print(f"\nTotal utterances to process: {len(df_input)}")

        # Process with existing reasoning
        df_results = process_dialogue_dataframe_with_existing_reasoning(df_input.copy(), model, tokenizer, model_id=args.model_id)

        print("\n--- Processing Complete ---")

        # Add probability calculation from logits (softmax)
        logit_columns = ['logit_explain_own_idea', 'logit_engage_others_low', 'logit_engage_others_medium', 'logit_engage_others_high', 'logit_uncorrelated']
        
        # Calculate probabilities using softmax for valid logits (not -inf)
        for idx, row in df_results.iterrows():
            logit_values = [row[col] for col in logit_columns]
            
            # Check if all logits are -inf (error case)
            if all(val == float('-inf') for val in logit_values):
                probabilities = [0.0, 0.0, 0.0, 0.0, 0.0]  # All zero probabilities for error cases
            else:
                # Replace -inf with very large negative number for softmax calculation
                logit_array = np.array([val if val != float('-inf') else -1000.0 for val in logit_values])
                exp_logits = np.exp(logit_array - np.max(logit_array))  # Numerical stability
                probabilities = exp_logits / np.sum(exp_logits)
            
            df_results.at[idx, 'prob_explain_own_idea'] = probabilities[0]
            df_results.at[idx, 'prob_engage_others_low'] = probabilities[1]
            df_results.at[idx, 'prob_engage_others_medium'] = probabilities[2]
            df_results.at[idx, 'prob_engage_others_high'] = probabilities[3]
            df_results.at[idx, 'prob_uncorrelated'] = probabilities[4]
        df_results.drop(columns=['utterance', 'reason'], errors='ignore', inplace=True)
        df_results.dropna(how='all', axis=1, inplace=True)
        df_results.to_csv(args.output_csv, index=False, encoding='utf-8-sig') # utf-8-sig for Excel compatibility
        print(f"\nResults saved to {args.output_csv}")
        print(f"Output includes: existing data plus logits and probabilities for each label")

        total_time = time.time() - start_time
        print(f"Total execution time: {total_time:.2f}s ({total_time/60:.2f}min).")
        if len(df_input)>0: print(f"Avg time/utterance: {total_time/len(df_input):.2f}s.")

    except Exception as e:
        print(f"An critical error occurred in main execution: {e}")
        import traceback; traceback.print_exc()

def debug_next_token_probs(model, tokenizer, prefix_text, top_k=20):
    """Utility: Print top-k next-token probabilities given a prefix.

    Parameters
    ----------
    model, tokenizer : The loaded HF model & tokenizer (same dtype/device as main code)
    prefix_text : str
        Full prompt string fed to the model *up to* the position where you want to inspect logits.
    top_k : int, optional
        Number of most-probable tokens to display (default 20).
    """
    model.eval()
    with torch.no_grad():
        inputs = tokenizer(prefix_text, return_tensors="pt")
        inputs = {k: v.to(model.device) for k, v in inputs.items()}
        outputs = model(**inputs)
        # Take logits of the last position (the next-token distribution)
        logits = outputs.logits[0, -1]
        probs = torch.softmax(logits, dim=-1)
        topk_probs, topk_indices = torch.topk(probs, top_k)
        topk_tokens = tokenizer.convert_ids_to_tokens(topk_indices.tolist())
        print(f"Top-{top_k} tokens after prefix (probabilities):")
        for tok, p in zip(topk_tokens, topk_probs):
            tok_clean = tok.replace('\u0120', '▁')  # visualise sentencepiece spaces if any
            print(f"{tok_clean:\<15} : {p.item():.5f}")
        return list(zip(topk_tokens, topk_probs.tolist()))


