// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// amen_count_nb_cpp
Rcpp::List amen_count_nb_cpp(arma::mat data, arma::cube X, const int ndim, const int niter, const int nburn, const int nthin, const int nprint, const double jump_beta, const double jump_alpha, const double jump_z, const double jump_w, const double jump_delta, const double r_init, const double pr_mean_beta, double pr_sd_beta, double pr_a_beta, double pr_b_beta, const double pr_a_alpha, const double pr_b_alpha, const double pr_mean_alpha, double pr_sd_alpha, const double pr_mean_delta, double pr_sd_delta, const double pr_sd_z, const double pr_sd_w, const double pr_mean_gamma, const double pr_sd_gamma, const double jump_r, const double pr_mean_r, double pr_sd_r, const double jump_gamma, const double pr_a_r_sd, const double pr_b_r_sd, const bool hierarchical_r, const bool fix_r, const bool fix, const double missing, const bool fixsd, const bool singledist, const bool vector, const bool covariate, const bool verbose);
RcppExport SEXP _nbamen_amen_count_nb_cpp(SEXP dataSEXP, SEXP XSEXP, SEXP ndimSEXP, SEXP niterSEXP, SEXP nburnSEXP, SEXP nthinSEXP, SEXP nprintSEXP, SEXP jump_betaSEXP, SEXP jump_alphaSEXP, SEXP jump_zSEXP, SEXP jump_wSEXP, SEXP jump_deltaSEXP, SEXP r_initSEXP, SEXP pr_mean_betaSEXP, SEXP pr_sd_betaSEXP, SEXP pr_a_betaSEXP, SEXP pr_b_betaSEXP, SEXP pr_a_alphaSEXP, SEXP pr_b_alphaSEXP, SEXP pr_mean_alphaSEXP, SEXP pr_sd_alphaSEXP, SEXP pr_mean_deltaSEXP, SEXP pr_sd_deltaSEXP, SEXP pr_sd_zSEXP, SEXP pr_sd_wSEXP, SEXP pr_mean_gammaSEXP, SEXP pr_sd_gammaSEXP, SEXP jump_rSEXP, SEXP pr_mean_rSEXP, SEXP pr_sd_rSEXP, SEXP jump_gammaSEXP, SEXP pr_a_r_sdSEXP, SEXP pr_b_r_sdSEXP, SEXP hierarchical_rSEXP, SEXP fix_rSEXP, SEXP fixSEXP, SEXP missingSEXP, SEXP fixsdSEXP, SEXP singledistSEXP, SEXP vectorSEXP, SEXP covariateSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type ndim(ndimSEXP);
    Rcpp::traits::input_parameter< const int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< const int >::type nburn(nburnSEXP);
    Rcpp::traits::input_parameter< const int >::type nthin(nthinSEXP);
    Rcpp::traits::input_parameter< const int >::type nprint(nprintSEXP);
    Rcpp::traits::input_parameter< const double >::type jump_beta(jump_betaSEXP);
    Rcpp::traits::input_parameter< const double >::type jump_alpha(jump_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type jump_z(jump_zSEXP);
    Rcpp::traits::input_parameter< const double >::type jump_w(jump_wSEXP);
    Rcpp::traits::input_parameter< const double >::type jump_delta(jump_deltaSEXP);
    Rcpp::traits::input_parameter< const double >::type r_init(r_initSEXP);
    Rcpp::traits::input_parameter< const double >::type pr_mean_beta(pr_mean_betaSEXP);
    Rcpp::traits::input_parameter< double >::type pr_sd_beta(pr_sd_betaSEXP);
    Rcpp::traits::input_parameter< double >::type pr_a_beta(pr_a_betaSEXP);
    Rcpp::traits::input_parameter< double >::type pr_b_beta(pr_b_betaSEXP);
    Rcpp::traits::input_parameter< const double >::type pr_a_alpha(pr_a_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type pr_b_alpha(pr_b_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type pr_mean_alpha(pr_mean_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type pr_sd_alpha(pr_sd_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type pr_mean_delta(pr_mean_deltaSEXP);
    Rcpp::traits::input_parameter< double >::type pr_sd_delta(pr_sd_deltaSEXP);
    Rcpp::traits::input_parameter< const double >::type pr_sd_z(pr_sd_zSEXP);
    Rcpp::traits::input_parameter< const double >::type pr_sd_w(pr_sd_wSEXP);
    Rcpp::traits::input_parameter< const double >::type pr_mean_gamma(pr_mean_gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type pr_sd_gamma(pr_sd_gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type jump_r(jump_rSEXP);
    Rcpp::traits::input_parameter< const double >::type pr_mean_r(pr_mean_rSEXP);
    Rcpp::traits::input_parameter< double >::type pr_sd_r(pr_sd_rSEXP);
    Rcpp::traits::input_parameter< const double >::type jump_gamma(jump_gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type pr_a_r_sd(pr_a_r_sdSEXP);
    Rcpp::traits::input_parameter< const double >::type pr_b_r_sd(pr_b_r_sdSEXP);
    Rcpp::traits::input_parameter< const bool >::type hierarchical_r(hierarchical_rSEXP);
    Rcpp::traits::input_parameter< const bool >::type fix_r(fix_rSEXP);
    Rcpp::traits::input_parameter< const bool >::type fix(fixSEXP);
    Rcpp::traits::input_parameter< const double >::type missing(missingSEXP);
    Rcpp::traits::input_parameter< const bool >::type fixsd(fixsdSEXP);
    Rcpp::traits::input_parameter< const bool >::type singledist(singledistSEXP);
    Rcpp::traits::input_parameter< const bool >::type vector(vectorSEXP);
    Rcpp::traits::input_parameter< const bool >::type covariate(covariateSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(amen_count_nb_cpp(data, X, ndim, niter, nburn, nthin, nprint, jump_beta, jump_alpha, jump_z, jump_w, jump_delta, r_init, pr_mean_beta, pr_sd_beta, pr_a_beta, pr_b_beta, pr_a_alpha, pr_b_alpha, pr_mean_alpha, pr_sd_alpha, pr_mean_delta, pr_sd_delta, pr_sd_z, pr_sd_w, pr_mean_gamma, pr_sd_gamma, jump_r, pr_mean_r, pr_sd_r, jump_gamma, pr_a_r_sd, pr_b_r_sd, hierarchical_r, fix_r, fix, missing, fixsd, singledist, vector, covariate, verbose));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_count_cpp
Rcpp::List log_likelihood_count_cpp(arma::mat data, const int ndim, arma::mat beta_est, arma::mat alpha_est, const double gamma_est, arma::mat z_est, arma::mat w_est, const double r_est, const double eta_est, const bool zeroinflate, const bool overdispersion, const bool vector);
RcppExport SEXP _nbamen_log_likelihood_count_cpp(SEXP dataSEXP, SEXP ndimSEXP, SEXP beta_estSEXP, SEXP alpha_estSEXP, SEXP gamma_estSEXP, SEXP z_estSEXP, SEXP w_estSEXP, SEXP r_estSEXP, SEXP eta_estSEXP, SEXP zeroinflateSEXP, SEXP overdispersionSEXP, SEXP vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const int >::type ndim(ndimSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_est(beta_estSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_est(alpha_estSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma_est(gamma_estSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z_est(z_estSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w_est(w_estSEXP);
    Rcpp::traits::input_parameter< const double >::type r_est(r_estSEXP);
    Rcpp::traits::input_parameter< const double >::type eta_est(eta_estSEXP);
    Rcpp::traits::input_parameter< const bool >::type zeroinflate(zeroinflateSEXP);
    Rcpp::traits::input_parameter< const bool >::type overdispersion(overdispersionSEXP);
    Rcpp::traits::input_parameter< const bool >::type vector(vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_count_cpp(data, ndim, beta_est, alpha_est, gamma_est, z_est, w_est, r_est, eta_est, zeroinflate, overdispersion, vector));
    return rcpp_result_gen;
END_RCPP
}
// calculate_waic_dic_procrustes_cpp
Rcpp::List calculate_waic_dic_procrustes_cpp(arma::mat data, arma::mat beta_samples, arma::mat alpha_samples, arma::vec gamma_samples, arma::vec r_samples, arma::cube z_proc, arma::cube w_proc, int ndim, bool overdispersion, bool zeroinflate, int missing, bool vector);
RcppExport SEXP _nbamen_calculate_waic_dic_procrustes_cpp(SEXP dataSEXP, SEXP beta_samplesSEXP, SEXP alpha_samplesSEXP, SEXP gamma_samplesSEXP, SEXP r_samplesSEXP, SEXP z_procSEXP, SEXP w_procSEXP, SEXP ndimSEXP, SEXP overdispersionSEXP, SEXP zeroinflateSEXP, SEXP missingSEXP, SEXP vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_samples(beta_samplesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_samples(alpha_samplesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma_samples(gamma_samplesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type r_samples(r_samplesSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type z_proc(z_procSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type w_proc(w_procSEXP);
    Rcpp::traits::input_parameter< int >::type ndim(ndimSEXP);
    Rcpp::traits::input_parameter< bool >::type overdispersion(overdispersionSEXP);
    Rcpp::traits::input_parameter< bool >::type zeroinflate(zeroinflateSEXP);
    Rcpp::traits::input_parameter< int >::type missing(missingSEXP);
    Rcpp::traits::input_parameter< bool >::type vector(vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_waic_dic_procrustes_cpp(data, beta_samples, alpha_samples, gamma_samples, r_samples, z_proc, w_proc, ndim, overdispersion, zeroinflate, missing, vector));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nbamen_amen_count_nb_cpp", (DL_FUNC) &_nbamen_amen_count_nb_cpp, 42},
    {"_nbamen_log_likelihood_count_cpp", (DL_FUNC) &_nbamen_log_likelihood_count_cpp, 12},
    {"_nbamen_calculate_waic_dic_procrustes_cpp", (DL_FUNC) &_nbamen_calculate_waic_dic_procrustes_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_nbamen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
