# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

amen_count_nb_cpp <- function(data, X, ndim, niter, nburn, nthin, nprint, jump_beta, jump_alpha, jump_z, jump_w, jump_delta, r_init, pr_mean_beta, pr_sd_beta, pr_a_beta, pr_b_beta, pr_a_alpha, pr_b_alpha, pr_mean_alpha, pr_sd_alpha, pr_mean_delta, pr_sd_delta, pr_sd_z, pr_sd_w, pr_mean_gamma, pr_sd_gamma, jump_r, pr_mean_r, pr_sd_r, jump_gamma, pr_a_r_sd, pr_b_r_sd, hierarchical_r, fix_r, fix, missing, fixsd, singledist, vector, covariate, verbose, adapt = TRUE, adapt_window = 50L, adapt_target_mh = 0.44, adapt_target_mala = 0.574, r_prior_phi = FALSE) {
    .Call(`_nbamen_amen_count_nb_cpp`, data, X, ndim, niter, nburn, nthin, nprint, jump_beta, jump_alpha, jump_z, jump_w, jump_delta, r_init, pr_mean_beta, pr_sd_beta, pr_a_beta, pr_b_beta, pr_a_alpha, pr_b_alpha, pr_mean_alpha, pr_sd_alpha, pr_mean_delta, pr_sd_delta, pr_sd_z, pr_sd_w, pr_mean_gamma, pr_sd_gamma, jump_r, pr_mean_r, pr_sd_r, jump_gamma, pr_a_r_sd, pr_b_r_sd, hierarchical_r, fix_r, fix, missing, fixsd, singledist, vector, covariate, verbose, adapt, adapt_window, adapt_target_mh, adapt_target_mala, r_prior_phi)
}

log_likelihood_count_cpp <- function(data, ndim, beta_est, alpha_est, gamma_est, z_est, w_est, r_est, eta_est, zeroinflate, overdispersion, vector = TRUE) {
    .Call(`_nbamen_log_likelihood_count_cpp`, data, ndim, beta_est, alpha_est, gamma_est, z_est, w_est, r_est, eta_est, zeroinflate, overdispersion, vector)
}

calculate_waic_dic_procrustes_cpp <- function(data, beta_samples, alpha_samples, gamma_samples, r_samples, z_proc, w_proc, ndim, z_mean_in, w_mean_in, overdispersion = FALSE, zeroinflate = FALSE, missing = -99L, vector = FALSE) {
    .Call(`_nbamen_calculate_waic_dic_procrustes_cpp`, data, beta_samples, alpha_samples, gamma_samples, r_samples, z_proc, w_proc, ndim, z_mean_in, w_mean_in, overdispersion, zeroinflate, missing, vector)
}

